### PR TITLE
Adding classes for inline radio buttons

### PR DESCRIPTION
**Pull request by nicomollet**
I added new classes, to be able to style each attribute, and make some radio buttons inline.

Thank you.

### CODE REVIEW

**Comment by Mantish** [comment]
Hi, thanks for the pull request
can you explain a bit more why these classes are needed? why can't you style the elements using the current markup?

**Comment by nicomollet** [comment]
I want to be able to have some variations with horizontal radio buttons, and some others vertical.
See this image for an example: https://imgur.com/a/COqAP

* The `<tr>` identifying the attribute doesn't have a class, so I can't make some inline and others not inline.
* The `.radio` class on the div is to be able to `display: inline-block` the radio buttons.

Do you think I can do this with the current markup?

**Comment by Mantish** [comment]
To style some attributes different you need the class on the `<tr>`
But I think the class on the `<div>` is not needed. You can target it with something like `.variations td > div`

**Comment by nicomollet** [comment]
Alright, I can do without the class on the `<div>` like you said, it's fine.

If you think the class on the `<tr>` doesn't hurt the project, I would appreciate the tweak ;)
I just reverted the class in my pull request. So you may publish it as it is.

Thank you.

**Pull request merged**
